---
- name: check if host is in target group before start tasks
  block:
    - name: debug if host is not in compute group
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is not in compute group, stopping execution"
      when: "'cinder' not in group_names"

    - name: stop running role on hosts not in compute
      meta: end_host
      when: "'cinder' not in group_names"

- name: ensure mark directory exists
  ansible.builtin.file:
    path: "{{ mark_dir_path }}"
    state: directory
    mode: '0755'

- name: setup LVM backend for cinder
  block:
    - name: ensure /dev/sdb is a physical volume
      community.general.lvg:
        vg: "cinder-volumes"
        pvs:
          - "/dev/sdb"
        state: present

    - name: ensure LVM filter allows only /dev/sdb
      ansible.builtin.replace:
        path: /etc/lvm/lvm.conf
        regexp: '^\s*filter\s*=.*$'
        replace: '    filter = [ "a/sdb/", "r/.*/"]'

- name: install some packages and configure cinder
  block:
    - name: install packages
      ansible.builtin.dnf:
        name: "{{ cinder_node_packages }}"
        state: latest

    - name: deploy template 
      ansible.builtin.template:
        src: "{{ cinder_conf_template_path.cinder_node_conf }}"
        dest: "{{ cinder_conf_path.cinder_conf }}"
      notify: 
        - restart openstack-cinder-volume
        - restart target
