#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/Skyline
- name: run controller tasks
  ansible.builtin.import_tasks: Skyline_controller.yml
  when: "'controller' in group_names"

- name: run skyline node tasks
  ansible.builtin.import_tasks: Skyline_node.yml
  when: "'skyline' in group_names"
