---
- name: check if host is in target group before start tasks
  block:
    - name: debug if host is not in controller group
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is not in compute group, stopping execution"
      when: "'controller' not in group_names"

    - name: stop running role on hosts not in controller
      meta: end_host
      when: "'controller' not in group_names"

- name: ensure mark directory exists
  ansible.builtin.file:
    path: "{{ mark_dir_path }}"
    state: directory
    mode: '0755'

- name: create Skyline db and db_user
  block:
    - name: create skyline_db
      community.mysql.mysql_db:
        login_user: root
        login_unix_socket: "{{ mariadb_unix_socket_path }}"
        name: "{{ skyline_db_conf.db_name }}"
        state: present

    - name: create skyline db_user
      community.mysql.mysql_user:
        login_user: root
        login_unix_socket: "{{ mariadb_unix_socket_path }}"
        name: "{{ skyline_db_conf.db_user_name }}"
        password: "{{ skyline_db_conf.db_user_password }}"
        priv: "{{ skyline_db_conf.db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      loop:
        - "localhost"
        - "%"

- name: create openstack skyline service user and assign admin role to skyline
  block:
    - name: create skyline user
      openstack.cloud.identity_user:
        name: skyline
        domain: default
        password: "{{ openstack_user_password.skyline }}"
        state: present

    - name: assgin admin role to skyline user
      openstack.cloud.role_assignment:
        user: skyline
        project: service
        role: admin
        state: present

