---
# tasks file for roles/Memcache
# this roles only runs in controller node , u need to check if the vars/main.yml contains var target_hostname
- name: check the hostname before start tasks
  block:
    - name: check if hostname is {{ target_hostname }}
      ansible.builtin.debug:
        msg: "the target host {{ inventory_hostname }}'s hostname 是 {{ ansible_hostname }}，not controller host，please check the hostname and rerun the role"
      when: ansible_hostname != target_hostname

    - name: stop running in wrong host
      meta: end_host
      when: ansible_hostname != target_hostname

- name: install memcached and deploy conf file to target host
  block:
    - name: install memcache packages
      ansible.builtin.dnf:
        name: "{{ memcache_packages }}"
        state: latest

    - name: configure memcache
      ansible.builtin.template:
        src: "{{ memcached_conf_template_path }}"
        dest: "{{ memcached_conf_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: start and enable memcache
      ansible.builtin.service:
        name: memcached
        state: started
        enabled: yes
