---
# tasks file for roles/RabbitMQ
# this roles only runs in controller node , u need to check if the vars/main.yml contains var target_hostname
- name: check the hostname before start tasks
  block:
    - name: check if hostname is {{ target_hostname }}
      ansible.builtin.debug:
        msg: "the target host {{ inventory_hostname }}'s hostname 是 {{ ansible_hostname }}，not controller host，please check the hostname and rerun the role"
      when: ansible_hostname != target_hostname

    - name: stop running in wrong host
      meta: end_host
      when: ansible_hostname != target_hostname 

- name: install RabbitMQ and add openstack user 
  block:
    - name: install rabbitmq_packages
      ansible.builtin.dnf:
        name: "{{ rabbitmq_packages }}"
        state: latest

    - name: start and enable rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Enable RabbitMQ management plugin
      community.rabbitmq.rabbitmq_plugin:
        name: rabbitmq_management
        state: enabled

    - name: add openstack user and set permissions
      community.rabbitmq.rabbitmq_user:
        name: openstack
        password: "{{ openstack_rabbitmq_user_password }}"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
        tags: none
        state: present

