---
# tasks file for roles/init_env
- name: ensure mark directory exists
  ansible.builtin.file:
    path: "{{ mark_dir_path }}"
    state: directory
    mode: '0755'

- name: configure add host_namppings to hosts file
  ansible.builtin.blockinfile:
    path: "{{ hosts_path }}"
    block: |
      {% for item in host_mappings %}
      {{ item.ip }} {{ item.name }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: stop firewall in target hosts(ubuntu's firewall is ufw)
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no

#we need to enable to download some packages that openstack needs      
- name: enable crb and install some packages
  block:
    - name: update all cache and packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: import openstack-GPG-file
      ansible.builtin.rpm_key:
        state: present
        key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Cloud

    - name: install necessary packages
      ansible.builtin.dnf:
        name: "{{ package_to_install }}"
        state: latest

          #if u use the offical repository,umay need to enable the crb repository
          #- name: enable crb repo
          #ansible.builtin.command: |
          #dnf config-manager --set-enabled crb

    - name: install openstack packages
      ansible.builtin.dnf:
        name: "{{ openstack_packages }}"
        state: latest
    
    - name: upgrade python-openstacksdk
      ansible.builtin.pip:
        name: openstacksdk
        state: latest

#chrony is the ntp tools we choose,u can use other ntp tools
- name: install and configure ntp service (use chrony)
  block: 
    - name: change chrony configuration from tempalte
      ansible.builtin.template:
        src: templates/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart_chronyd

    - name: enable set_ntp_yes in timedatactl
      ansible.builtin.command: timedatectl set-ntp yes

    - name: check chronyd's ntp server
      ansible.builtin.command: |
        chronyc sources -v | grep '^\^\*'
      register: chrony_server
      changed_when: false
      ignore_errors: yes

#this block is used to make each node trust each other 
- name: ssh_trust tasks 
  block:
    - name: Generate SSH key (if not exists)
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
        mode: '0600'

    - name: Read public key
      ansible.builtin.slurp:
        src: /root/.ssh/id_rsa.pub
      register: ssh_pub_key

    - name: Save public key to hostvars
      ansible.builtin.set_fact:
        node_pub_key: "{{ ssh_pub_key.content | b64decode }}"

    - name: Aggregate all public keys
      ansible.builtin.set_fact:
        all_pub_keys: >-
          {{ hostvars | dict2items
          | selectattr('value.node_pub_key', 'defined')
          | map(attribute='value.node_pub_key') | list }}
      run_once: true
      delegate_to: localhost

    - name: Distribute all public keys to each node
      ansible.builtin.authorized_key:
        user: root
        key: "{{ item }}"
      loop: "{{ all_pub_keys }}"

- name: disable SELinux
  block: 
    - name: disable all node's selinux
      ansible.posix.selinux:
        state: disabled
        policy: targeted

    - name: reboot all nodes to apply changes
      ansible.builtin.reboot:
        msg: "Reboot to fully disable SELinux"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: selinux_reboot_required | default(true)


