---
# handlers file for roles/Neutron
- name: restart openstack-nova-api service
  ansible.builtin.service:
    name: openstack-nova-api.service
    state: restarted
    enabled: yes

- name: restart openstack-nova-compute 
  ansible.builtin.service:
    name: openstack-nova-compute.service
    state: restarted
    enabled: yes

- name: restart neutron-openvswitch-agent
  ansible.builtin.service:
    name: neutron-openvswitch-agent.service
    state: restarted
    enabled: yes
