#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/Cinder
- name: start and enable cinder services
  ansible.builtin.service:
    state: started
    name: "{{ item }}"
    enabled: yes
  loop:
    - openstack-cinder-api.service
    - openstack-cinder-scheduler.service
    - openstack-cinder-volume.service

- name: restart openstack-nova-api
  ansible.builtin.service:
    state: restarted
    name: openstack-nova-api.service
    enabled: yes

- name: restarted httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: yes

- name: restart openstack-cinder-volume     
  ansible.builtin.service:
    name: openstack-cinder-volume.service
    state: restarted
    enabled: yes 

- name: restart target  
  ansible.builtin.service:
    name: target
    state: restarted
    enabled: yes
