---
- name: check if host is in target group before start tasks
  block:
    - name: debug if host is not in compute group
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is not in compute group, stopping execution"
      when: "'compute' not in group_names"

    - name: stop running role on hosts not in compute
      meta: end_host
      when: "'compute' not in group_names"

- name: ensure mark directory exists
  ansible.builtin.file:
    path: "{{ mark_dir_path }}"
    state: directory
    mode: '0755'

- name: install nova-compute packages and configure openstack-nova-compute
  block: 
    - name: install nova-compute packages
      ansible.builtin.dnf:
        name: "{{ nova_compute_packages }}"
        state: latest

    - name: ensure the libvirtd is running
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: yes
    
    - name: use templates to deploy conf file
      ansible.builtin.template:
        src: "{{ nova_compute_conf_template_path }}"
        dest: "{{ nova_compute_conf_path }}"
    
    - name: restart nova-compute
      ansible.builtin.service:
        name: openstack-nova-compute
        state: restarted
        enabled: yes
